# Generated by Django 4.2.3 on 2023-08-04 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('diagnostic', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('food_like', models.CharField(blank=True, max_length=50, null=True)),
                ('food_dislike', models.CharField(blank=True, max_length=50, null=True)),
                ('event_like', models.CharField(blank=True, max_length=50, null=True)),
                ('event_dislike', models.CharField(blank=True, max_length=50, null=True)),
                ('phrase', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_angry', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('home_sad', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('home_panic', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('play_angry', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('play_sad', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('play_panic', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('school_angry', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('school_sad', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('school_panic', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('eat_angry', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('eat_sad', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('eat_panic', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('shop_angry', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('shop_sad', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('shop_panic', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('car_angry', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('car_sad', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('car_panic', models.IntegerField(choices=[(0, 'False'), (1, 'True'), (2, '未设置')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='webapp/img/default_avatar.png', upload_to='webapp/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
