# Generated by Django 4.2.3 on 2023-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to='avatar'),
        ),
    ]
