# Generated by Django 4.2.3 on 2023-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_userprofile_current_record_id_recordanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordanswer',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
