# Generated by Django 4.2.3 on 2023-08-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_recordanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_char',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
