# Generated by Django 4.2.3 on 2023-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_userprofile_ai_char_userprofile_ai_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
