# Generated by Django 4.2.3 on 2023-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_userprofile_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordanswer',
            name='gpt_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='gpt_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='gpt_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='q1_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='q2_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='q3_init',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
