# Generated by Django 4.2.3 on 2023-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_recordanswer_gpt_1_recordanswer_gpt_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordanswer',
            name='gpt_sum',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='summary_init',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
