# Generated by Django 4.2.3 on 2023-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_recordanswer_gpt_sum_recordanswer_summary_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordanswer',
            name='story_p1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='story_p2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='story_p3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordanswer',
            name='story_p4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
